---
- hosts: all
  become: true
  tasks:

  - name: update repository index Ubuntu
    apt: 
       update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 and php packages for Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: update repository index for CentOs
    dnf:
      update_cache: yes
    when: ansible_os_family == "RedHat"

  - name: install apache and php packages for Centos
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_os_family == "RedHat"
