---
  - hosts: all
    become: true
    tasks:

     - name: install apache2 package
       apt:
           name: apache2
     - name: Ping
       ansible.builtin.ping:
     - name: add PHP support for apache
       apt:
           name: libapache2-mod-php
     - name: update repository index
       apt:
         update_cache: yes
